name: Movies Prod Workflow
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Build & deploy application
        uses: actions/checkout@v4
      - run: |
          docker ps
          docker stop $(docker ps -a -q)
          docker image prune -f
          docker container prune -f
          docker container ls -a
          docker build -t movies-python-app .
          docker run --name movies-app-${{github.run_number}} -d -p 80:5000 movies-python-app
          docker container ls -a
