name: Movies Prod Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: 
      group: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: |
          ls 
          ls -la