name: Movies Prod Workflow
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build & deploy application
      - run: |
          docker rmi $(docker images -q)
          docker kill $(docker ps -q)
          docker container ls -a
          docker build -t movies-python-app .
          docker run --name movies-app -d -p 80:5000 movies-python-app
